abstract class AppState{}
class InitState extends AppState{}
class CreateState extends AppState{}
class AInsertState extends AppState{}
class AShowState extends AppState{}
class AUpdateState extends AppState{}
class ADeleteState extends AppState{}
class CInsertState extends AppState{}
class CShowState extends AppState{}
class CUpdateState extends AppState{}
class CDeleteState extends AppState{}
class TInsertState extends AppState{}
class TShowState extends AppState{}
class TUpdateState extends AppState{}
class TDeleteState extends AppState{}
class MesInsertState extends AppState{}
class MesShowState extends AppState{}
class MetInsertState extends AppState{}
class MetShowState extends AppState{}
class EmployeeTasksState extends AppState{}
class UpdateSalary extends AppState{}
class UpdateAdminData extends AppState{}
class UpdateClientData extends AppState{}
